title: Eliot Brown's Resume
author: GitHub User
email: eliotb26@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my resume and thanks for being here. I am currently a sophomore at New York University studying Computer Engineering with 
 minors in Cybersecurity and Mathmatics. 

# social links
twitter_username: your-twitter-handle
github_username:  eliotb26

show_excerpts: true # set to false to remove excerpts on the homepage
