title: Eliot Brown Resume
author: Eliot Brown
email: eliotb26@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  A sophomore at New York University studying Computer Engineering with minors in Cybersecurity and Mathmatics.
  One of the few social coders on the planet. 
  

# social links
twitter_username: 
github_username:  eliotb26

show_excerpts: true # set to false to remove excerpts on the homepage
